### ISSUE TITLE
AttributeError: type object 'impatchify' has no attribute '_impatchify__patchifyImg2'

### ISSUE THREAD

**Issue by MartinHasal** [MartinHasal/RetinaVesselSeg_tf#7]
During run `pipeline_unet_vgg16`

` Traceback (most recent call last):

  File "D:\Dropbox (ARG@CS.FEI.VSB)\Dataset - retiny\images_from_doctor\ML\SEGMENTATION\RetinaVesselSeg_tf\pipeline_unet_vgg16.py", line 33, in <module>
    ds_train = da.getTrainingDataset()

  File "D:\Dropbox (ARG@CS.FEI.VSB)\Dataset - retiny\images_from_doctor\ML\SEGMENTATION\RetinaVesselSeg_tf\procs\adapter.py", line 276, in getTrainingDataset
    self.__createDataset()

  File "D:\Dropbox (ARG@CS.FEI.VSB)\Dataset - retiny\images_from_doctor\ML\SEGMENTATION\RetinaVesselSeg_tf\procs\adapter.py", line 240, in __createDataset
    np_imgs, np_masks = self.__loadImages()

  File "D:\Dropbox (ARG@CS.FEI.VSB)\Dataset - retiny\images_from_doctor\ML\SEGMENTATION\RetinaVesselSeg_tf\procs\adapter.py", line 201, in __loadImages
    src_patches = impatchify.getPatches(

  File "D:\Dropbox (ARG@CS.FEI.VSB)\Dataset - retiny\images_from_doctor\ML\SEGMENTATION\RetinaVesselSeg_tf\procs\impatch.py", line 95, in getPatches
    fn_patch = impatchify.__pathifyOverlap(overlap_ratio) if overlap_ratio > 0. else impatchify.__patchifyImg2

AttributeError: type object 'impatchify' has no attribute '_impatchify__patchifyImg2' `

Please add `__patchifyImg2` in impatch.py, check line 95 inside

**Comment by MartinHasal** [comment]
Solved, removed old function  '_impatchify__patchifyImg2'

**Comment by mpecha** [comment]
Sorry, this was my fault. I missed to check if the code works after refactoring.
